version: '3'

services:
  backend:
    env_file:
      - .env.production
    image: sourtimes-backend
    build:
      context: .
      dockerfile: Dockerfile.production
      args:
        - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/usr/local/app/
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
