version: '3'

services:
  backend:
    env_file:
      - .env.development
    image: sourtimes-backend
    build:
      context: .
      dockerfile: Dockerfile.development
      args:
        - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/usr/local/app/
    restart: always
  mongo:
    env_file:
      - .env.development
    image: mongo:latest
    ports:
      - '27017:27017'
